server:
  port: 8888

logging:
  level:
    root: INFO

eureka:
  instance:
    prefer-ip-address: true
    #instance-id: ${spring.cloud.client.ipAddress}:${server.port}:${random.value}
    # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 30
    # 续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 90
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  application:
    name: eureka-consumer